---

- hosts: docker
  name: "Docker Restart Playbook"
  tasks:
    # Docker system service
    - name: "Restart docker daemon"
      tags:
        - "docker"
      service:
        name: "docker"
        state: restarted
      when: inventory_hostname in groups.docker

    # Proxy
    - name: "Restart reverseproxy container"
      tags:
        - "proxy"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/inverseproxy"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/inverseproxy"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker

    # Auth
    - name: "Restart auth container"
      tags:
        - "auth"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/auth"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/auth"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_auth

    # Nagios images
    # Nagios
    - name: "Restart nagios container"
      tags:
        - "nagios"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/nagios"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/nagios"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_nagios

    # Nextcloud
    - name: "Restart nextcloud container"
      tags:
        - "nextcloud"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/nextcloud"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/nextcloud"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_nextcloud

    ## Odoo
    # Whitelists
    - name: "Restart odoo whitelists container"
      tags:
        - "whitelists"
      block:
        - name: Remove container
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: "whitelists.yaml"
            project_name: "whitelists"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: "whitelists.yaml"
            project_name: "whitelists"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_odoo and restrict_internet_access and whitelisted_urls is defined

    # Odoo
    - name: "Restart Odoo container"
      tags:
        - "odoo"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/{{ item.key }}"
            remove_orphans: true
            state: absent
          with_dict: "{{ odoo_instances }}"
          loop_control:
              label: "{{ item.key }}"
          when: not (item.value.prod_instance | default(false) == item.key) and (odoo_instance is undefined or item.key == odoo_instance)
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/{{ item.key }}"
            recreate: always
            remove_orphans: true
            state: present
          with_dict: "{{ odoo_instances }}"
          loop_control:
              label: "{{ item.key }}"
          when: not (item.value.prod_instance | default(false) == item.key) and (odoo_instance is undefined or item.key == odoo_instance)
          async: 120
          poll: 10

    # Draw.io
    - name: "Restart Draw.io container"
      tags:
        - "drawio"
        - "services_libres"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: "draw.io.yaml"
            project_name: "draw.io"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: "draw.io.yaml"
            project_name: "draw.io"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_drawio

    # Etherpad
    - name: "Restart Etherpad container"
      tags:
        - "etherpad"
        - "services_libres"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/etherpad"
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker/etherpad"
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_etherpad

    # Framadate
    - name: "Restart Framadate container"
      tags:
        - "framadate"
        - "services_libres"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: framadate.yaml
            project_name: framadate
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: framadate.yaml
            project_name: framadate
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_framadate

    # Jitsi
    - name: "Restart Jitsi container"
      tags:
        - "jitsi"
        - "services_libres"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: jitsi.yaml
            project_name: jitsi
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: jitsi.yaml
            project_name: jitsi
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_jitsi

    # Privatebin
    - name: "Restart Privatebin container"
      tags:
        - "privatebin"
        - "services_libres"
      block:
        - name: "Remove container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: privatebin.yaml
            project_name: privatebin
            remove_orphans: true
            state: absent
          async: 120
          poll: 10

        - name: "Start container"
          community.docker.docker_compose_v2:
            project_src: "/home/docker"
            files: privatebin.yaml
            project_name: privatebin
            recreate: always
            remove_orphans: true
            state: present
          async: 120
          poll: 10
      when: inventory_hostname in groups.docker_privatebin
