---
collections:
  - name: ansible.posix
    version: '1.2.0'
  - name: community.docker
    version: '1.8.0'
  - name: community.general
    version: '3.3.2'

roles:
  - src: https://sources.le-filament.com/lefilament/ansible-roles/backup_server_conf
    scm: git
    version: v1.0.1
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_auth
    scm: git
    version: v1.0.2
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_drawio
    scm: git
    version: v1.0.1
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_etherpad
    scm: git
    version: v1.0.2
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_framadate
    scm: git
    version: v1.0.2
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_jitsi
    scm: git
    version: v1.0.0
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_nagios
    scm: git
    version: v1.1.1
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_nextcloud
    scm: git
    version: v1.1.5
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_odoo
    scm: git
    version: v1.0.13
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_owncloud
    scm: git
    version: v1.0.4
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_privatebin
    scm: git
    version: v1.0.2
  - src: https://sources.le-filament.com/lefilament/ansible-roles/docker_server
    scm: git
    version: v1.4.0
  - src: https://sources.le-filament.com/lefilament/ansible-roles/filebeat
    scm: git
    version: v1.0.0
  - src: https://sources.le-filament.com/lefilament/ansible-roles/gitlab
    scm: git
    version: v1.0.2
  - src: https://sources.le-filament.com/lefilament/ansible-roles/init_server
    scm: git
    version: v1.0.1
  - src: https://sources.le-filament.com/lefilament/ansible-roles/nagios_nrpe
    scm: git
    version: v1.0.3
  - src: https://sources.le-filament.com/lefilament/ansible-roles/server_security
    scm: git
    version: v1.0.1
