# Start from Debian Stretch
FROM debian:stretch
MAINTAINER Le Filament

# Change SSO DOMAIN here
ENV SSODOMAIN={{ sso_url }} \
    DEBIAN_FRONTEND=noninteractive

EXPOSE 80

COPY lemonldap-ng.list /

# Update system
RUN apt-get -y update \
    && apt-get -y install wget apt-transport-https gnupg liblasso-perl \
    && apt-get -y dist-upgrade  \
    && echo "# Install LemonLDAP::NG repo" \
    && mv lemonldap-ng.list /etc/apt/sources.list.d/ \
    && wget -O - https://lemonldap-ng.org/_media/rpm-gpg-key-ow2 | apt-key add - \
    && apt-get -y update \
    && echo "# Install LemonLDAP::NG package" \
    && apt-get -y install apache2 libapache2-mod-perl2 libapache2-mod-fcgid lemonldap-ng lemonldap-ng-fr-doc \
    && echo "# Change SSO Domain" \
    && sed -i "s/example\.com/${SSODOMAIN}/g" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.js /var/lib/lemonldap-ng/test/index.pl \
    && sed -i "s/auth.${SSODOMAIN}/${SSODOMAIN}/g" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.js /var/lib/lemonldap-ng/test/index.pl \
    && sed -i "s/reload.${SSODOMAIN}/handler.${SSODOMAIN}/g" /etc/lemonldap-ng/* /var/lib/lemonldap-ng/conf/lmConf-1.js /var/lib/lemonldap-ng/test/index.pl \
    && echo "# Enable sites" \
    && a2ensite handler-apache2.conf \
    && a2ensite portal-apache2.conf \
    && a2ensite manager-apache2.conf \
    && a2dismod mpm_event \
    && a2enmod fcgid perl alias rewrite headers mpm_prefork proxy proxy_http \
    && echo "# Remove cached configuration" \
    && rm -rf /tmp/lemonldap-ng-config \
    && rm -fr /var/lib/apt/lists/* \
    && mkdir /vhosts

{% if inventory_hostname in groups['docker_nagios'] %}
# Add Nagios website protection
COPY nagios.conf /etc/apache2/sites-available/
RUN a2ensite nagios.conf

{% endif %}
VOLUME /var/lib/lemonldap-ng/conf
VOLUME /var/lib/lemonldap-ng/psessions
VOLUME /var/lib/lemonldap-ng/sessions

CMD "/usr/sbin/apache2ctl" "-D" "FOREGROUND"
