---

- name: Install NRPE dependencies
  package:
    name: ['git', 'autoconf', 'gcc', 'libc6', 'libmcrypt-dev', 'make', 'libssl-dev', 'wget']
    state: present
  when: ansible_os_family == "Debian"

- name: Install NRPE dependencies
  package:
    name: ['git', 'gcc', 'glibc', 'glibc-common', 'openssl', 'openssl-devel', 'perl', 'wget']
    state: present
  when: ansible_os_family == "RedHat"

#--------------------------------------------------
# CREATE NAGIOS USERS
#--------------------------------------------------
- name: Create nagios system group
  group:
    name: nagios
  tags: nagios_install

- name: Create nagios command system group
  group:
    name: nagcmd
  tags: nagios_install

- name: Create nagios system user
  user:
    system: yes
    name: nagios
    group: nagios
    groups: nagcmd
  tags: nagios_install

#--------------------------------------------------
# INSTALLATION NAGIOS NRPE
#--------------------------------------------------
- name: Retrieve and Uncompress Nagios NRPE
  unarchive:
    src: https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
    remote_src: yes
    dest: /root/
    creates: /root/nrpe-3.2.1
  register: nrpe_downloaded

- name: Initial configuration Nagios NRPE
  shell: ./configure --enable-command-args --with-nagios-user=nagios --with-nagios-group=nagios --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu --enable-ssl
  args:
    chdir: /root/nrpe-3.2.1
  async: 500
  poll: 10
  when: nrpe_downloaded.skipped is not defined and nrpe_downloaded.changed

- name: Make nagios NRPE
  make:
    chdir: /root/nrpe-3.2.1
    target: "{{ item }}"
  with_items:
    - all
    - install
    - install-config
    - install-init
  async: 120
  poll: 10
  when: nrpe_downloaded.skipped is not defined and nrpe_downloaded.changed

- name: Systemd daemon reload
  systemd: daemon-reload=yes
  when: nrpe_downloaded.skipped is not defined and nrpe_downloaded.changed

- name: Make NRPE start with system
  service:
    name: nrpe
    state: started
    enabled: true

- name: Check that nrpe is defined in services
  lineinfile:
    name: /etc/services
    regexp: '^nrpe'
    line: "nrpe            5666/tcp                        # Nagios Remote Plugin Executor"

#--------------------------------------------------
# INSTALLATION NAGIOS PLUGINS
#--------------------------------------------------
- name: Retrieve and Uncompress Nagios Plugins
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.2.1/nagios-plugins-2.2.1.tar.gz
    remote_src: yes
    dest: /root/
    creates: /root/nagios-plugins-2.2.1
  register: plugins_downloaded

- name: Initial configuration Nagios Plugins
  shell: ./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-openssl
  args:
    chdir: /root/nagios-plugins-2.2.1
  async: 500
  poll: 10
  when: plugins_downloaded.skipped is not defined and plugins_downloaded.changed

- name: Make nagios-plugins
  make:
    chdir: /root/nagios-plugins-2.2.1
    target: "{{ item }}"
  with_items:
    - all
    - install
  async: 120
  poll: 10
  when: plugins_downloaded.skipped is not defined and plugins_downloaded.changed

#--------------------------------------------------
# CONFIGURATION NRPE
#--------------------------------------------------
- name: Push NRPE configuration file
  template:
    src: nrpe.cfg.j2
    dest: /usr/local/nagios/etc/nrpe.cfg
    owner: nagios
    group: nagios
    mode: '0644'
  notify: restart nrpe
  tags: nrpe_config

#--------------------------------------------------
# AJOUT CUSTOM SCRIPTs
#--------------------------------------------------
- name: get custom scripts from gitlab
  git: repo="https://sources.le-filament.com/lefilament/nagios-plugin.git" dest="/usr/local/nagios/libexec/custom-plugin"

- name: set file rights on custom plugins
  file: name={{ item }} mode=0555
  with_items:
    - /usr/local/nagios/libexec/custom-plugin/check_cloud_storage.sh
    - /usr/local/nagios/libexec/custom-plugin/check_mountpoint.sh
    - /usr/local/nagios/libexec/custom-plugin/check_newest_file_age.sh
    - /usr/local/nagios/libexec/custom-plugin/check_odoo_storage.sh

- name: add check_docker script
  get_url:
    url: https://raw.githubusercontent.com/timdaman/check_docker/master/check_docker/check_docker.py
    dest: /usr/local/nagios/libexec/custom-plugin/check_docker.py
    mode: '0555'
  when: inventory_hostname in groups.docker

- name: add check_mdstat script
  get_url:
    url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=5423&cf_id=24
    dest: /usr/local/nagios/libexec/custom-plugin/check_mdstat.sh
    mode: '0555'
  when: raid_config is defined

- name: add check_mem.pl script
  get_url:
    url: https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
    dest: /usr/local/nagios/libexec/custom-plugin/check_mem.pl
    mode: '0555'

- name: add check_version script
  get_url:
    url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=1785&cf_id=24
    dest: /usr/local/nagios/libexec/custom-plugin/check_version.sh
    mode: '0555'

- name: add check_fail2ban script
  get_url:
    url: https://raw.githubusercontent.com/n1tr0-5urf3r/icinga2-scripts/master/plugins/check_fail2ban
    dest: /usr/local/nagios/libexec/custom-plugin/check_fail2ban
    mode: '0555'
  tags: nrpe_config

- name: add nagios to www-data group
  user:
    name: nagios
    groups: www-data
    append: yes
  when: inventory_hostname in groups.owncloud_server | union(groups.docker_owncloud) | union(groups.docker_nextcloud)

- name: add nagios to docker group
  user:
    name: nagios
    groups: docker
    append: yes
  when: inventory_hostname in groups.docker
